# -*- coding: utf-8 -*-
"""Estagio_Target.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mvxgAGWl6wzoAKRVvJLh-9LG6hIiV0VF
"""

#Exercicío 3

import json

with open('dados.json', 'r') as faturamento_diario:
    dados = json.load(faturamento_diario)

valores = [dia['valor'] for dia in dados if dia['valor'] > 0]
menor_faturamento = min(valores)
maior_faturamento = max(valores)
media_mensal = sum(valores) / len(valores)
fat_superior_media = sum(1 for valor in valores if valor > media_mensal)

print(f"Menor faturamento diário: R${menor_faturamento:.2f}")
print(f"Maior faturamento diário: R${maior_faturamento:.2f}")
print(f"Número de dias com faturamento acima da média mensal: {fat_superior_media}")