# -*- coding: utf-8 -*-
"""Estagio_Target.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mvxgAGWl6wzoAKRVvJLh-9LG6hIiV0VF
"""

#Exercicío 1

INDICE = 13
SOMA = 0
K = 0

while K < INDICE:
    K = K + 1
    SOMA = SOMA + K

print(SOMA)