# -*- coding: utf-8 -*-
"""Estagio_Target.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mvxgAGWl6wzoAKRVvJLh-9LG6hIiV0VF
"""

#Exercicío 5

string_normal = input("Digite uma string: ")
vetor_invertido = []

indice = len(string_normal) - 1
while indice >= 0:
    vetor_invertido.append(string_normal[indice])
    indice -= 1

string_invertida = ''.join(vetor_invertido)
print(string_invertida)